pages:
  stage: deploy
  script:
    - mkdir .public
    - cp index.html .public
    - cp FavouriteQuotes.json .public
    - cp app.js .public
    - cp style.css .public
    - cp favicon.ico .public
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
